### ISSUE TITLE
大哥厉害

### ISSUE THREAD

**Issue by lzppp** [hf136/hf136.github.io#1]
大哥无敌，大哥牛逼有个问题
http://www.wuyueqiu.top/2018/11/18/neural-network/#more
神经元一般由一个线性回归和一个激活函数（非线性部分）构成
是什么

**Comment by wyq136** [comment]
可以先看看前面的线性回归和逻辑回归等几篇文章。
不过我现在写的东西偏向于整理知识，可能不太适合于初学者看。
